# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d3dd51f98366aa60f8bb4dabd24db660839d8deebd53243905c01278b85b8eef7045ec5d2fa9b1cd03c431291d9363557abaec33d41d2f46f5ed41d14cd2248

test:
  secret_key_base: d57c34f24387c688d64f61126c6769ff2b8c1929d642dafdae6b5bb67339504ba66e7fb3dd7af3548cf93ff51bdf411b9b4cf0ca2b6aa546cf7535bdbafbac74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
